/* Scintilla source code edit control */
/** @file SciLexer.h
 ** Interface to the added lexer functions in the SciLexer version of the edit control.
 **/
/* Copyright 1998-2002 by Neil Hodgson <neilh@scintilla.org>
 * The License.txt file describes the conditions under which this software may be distributed. */

/* Most of this file is automatically generated from the Scintilla.iface interface definition
 * file which contains any comments about the definitions. HFacer.py does the generation. */

#ifndef SCILEXER_H
#define SCILEXER_H

/* SciLexer features - not in standard Scintilla */

#define SCLEX_CONTAINER 0
#define SCLEX_NULL 1
#define SCLEX_TS 2
#define SCLEX_AUTOMATIC 1000

#define SCE_TS_DEFAULT 0
#define SCE_TS_COMMENT 1
#define SCE_TS_NUMBER 2
#define SCE_TS_WORD1 3
#define SCE_TS_STRING 4
#define SCE_TS_OPERATOR 5
#define SCE_TS_IDENTIFIER 6
#define SCE_TS_WORD2 7
#define SCE_TS_WORD3 8
#define SCE_TS_WORD4 9
#define SCE_TS_WORD5 10
#define SCE_TS_WORD6 11
#define SCE_TS_WORD7 12
#define SCE_TS_WORD8 13


#endif
